insert into vehicles (vehicle_id, name, license, vehicle_type, vehicle_year, vehicle_status) values
                                                                                                 (1, 'Cobus 3000', 'BUS-201', 'SHUTTLE_BUS', 2018, 'OPERATIONAL'),
                                                                                                 (2, 'Goldhofer AST-1X', 'PBT-312', 'PUSHBACK_TRUCK', 2016, 'UNDER_MAINTENANCE'),
                                                                                                 (3, 'Douglas DC-12', 'TUG-404', 'TUG', 2015, 'IN_REPAIR'),
                                                                                                 (4, 'Scania FuelMaster', 'FUEL-555', 'FUEL_TRUCK', 2019, 'FUELING'),
                                                                                                 (5, 'Hi-Lift Alpha', 'FOOD-198', 'FOOD_SERVICE_TRUCK', 2017, 'CLEANING'),
                                                                                                 (6, 'TLD BL30', 'BELT-623', 'BELT_LOADER', 2020, 'OPERATIONAL'),
                                                                                                 (7, 'Vestergaard Elephant Beta', 'DEI-777', 'DEICING_TRUCK', 2018, 'UNDER_INSPECTION'),
                                                                                                 (8, 'Rosenbauer Panther', 'FIRE-911', 'FIRE_TRUCK', 2021, 'OPERATIONAL'),
                                                                                                 (9, 'Neoplan Apron Bus', 'BUS-401', 'SHUTTLE_BUS', 2015, 'AWAITING_INSPECTION'),
                                                                                                 (10, 'Mobile Lounge APM-300', 'ML-334', 'MOBILE_LOUNGE', 2014, 'CLEANING'),
                                                                                                 (11, 'AMSS Ambulift 6000', 'AMB-663', 'AMBULIFT', 2017, 'OPERATIONAL'),
                                                                                                 (12, 'MAN TGM Maintenance', 'MAINT-527', 'MAINTENANCE_TRUCK', 2016, 'UNDER_MAINTENANCE'),
                                                                                                 (13, 'Ford Explorer Security', 'SEC-102', 'SECURITY_VEHICLE', 2019, 'OPERATIONAL'),
                                                                                                 (14, 'Schmidt CJS Compact', 'SWP-840', 'AIRFIELD_SWEEPER', 2022, 'OPERATIONAL'),
                                                                                                 (15, 'Mercedes Econic Fueler', 'FUEL-859', 'FUEL_TRUCK', 2020, 'FUELING'),
                                                                                                 (16, 'TLD TMX-150', 'TUG-738', 'TUG', 2018, 'IN_REPAIR'),
                                                                                                 (17, 'Vestergaard Elephant My', 'DEI-902', 'DEICING_TRUCK', 2019, 'AWAITING_INSPECTION'),
                                                                                                 (18, 'Oshkosh Striker 3000', 'FIRE-118', 'FIRE_TRUCK', 2021, 'OPERATIONAL'),
                                                                                                 (19, 'Neoplan N912L', 'BUS-509', 'SHUTTLE_BUS', 2016, 'OUT_OF_SERVICE'),
                                                                                                 (20, 'Cobus 2700S', 'BUS-223', 'SHUTTLE_BUS', 2017, 'UNDER_INSPECTION'),
                                                                                                 (21, 'Boeing 737-800', 'AC-737', 'AIRCRAFT', 2015, 'UNDER_INSPECTION'),
                                                                                                 (22, 'Airbus Helicopters H135', 'HEL-135', 'HELICOPTER', 2018, 'OPERATIONAL');

